ENABLE_SECUREMSM_DLKM := true
ENABLE_SECUREMSM_QTEE_DLKM := true
ENABLE_QCEDEV_FE := false
ENABLE_SST_INVOKE_TEST := false
ENABLE_HDCP_TEST := false
ENABLE_SECCAM_TEST := false
ENABLE_SI_CORE_TEST := false

ifeq ($(TARGET_KERNEL_DLKM_DISABLE), true)
  ifeq ($(TARGET_KERNEL_DLKM_SECURE_MSM_OVERRIDE), false)
      ENABLE_SECUREMSM_DLKM := false
  endif
  ifeq ($(TARGET_KERNEL_DLKM_SECUREMSM_QTEE_OVERRIDE), false)
      ENABLE_SECUREMSM_QTEE_DLKM := false
  endif
endif

ifeq ($(ENABLE_SECUREMSM_DLKM), true)
  ENABLE_QCRYPTO_DLKM := true
  ENABLE_HDCP_QSEECOM_DLKM := true
  ENABLE_QRNG_DLKM := true
  ifeq ($(TARGET_USES_SMMU_PROXY), true)
    ENABLE_SMMU_PROXY := true
  endif #TARGET_USES_SMMU_PROXY
  ifeq ($(filter $(TARGET_BOARD_PLATFORM), canoe vienna),$(TARGET_BOARD_PLATFORM))
    ENABLE_TMECOM_INTF_DLKM := true
  endif
  #enable QCEDEV_FE driver only on Automotive Lemans HQX LA GVM.
  ifeq ($(ENABLE_HYP),true)
    ifeq ($(TARGET_BOARD_PLATFORM),gen4)
      ifneq ($(TARGET_USES_GY), true)
        ENABLE_QCEDEV_FE := true
      endif #TARGET_USES_GY
    endif #TARGET_BOARD_PLATFORM
  endif #ENABLE_HYP
endif #ENABLE_SECUREMSM_DLKM

ifeq ($(ENABLE_SECUREMSM_QTEE_DLKM), true)
  ENABLE_SMCINVOKE_DLKM := true
  ENABLE_TZLOG_DLKM := true
  #Enable Qseecom if TARGET_ENABLE_QSEECOM or TARGET_BOARD_AUTO is set to true
  ifneq (, $(filter true, $(TARGET_ENABLE_QSEECOM) $(TARGET_BOARD_AUTO)))
    ENABLE_QSEECOM_DLKM := true
  endif #TARGET_ENABLE_QSEECOM OR TARGET_BOARD_AUTO
endif #ENABLE_SECUREMSM_QTEE_DLKM

ifeq ($(TARGET_USES_GY), true)
  ENABLE_QCRYPTO_DLKM := false
  ENABLE_HDCP_QSEECOM_DLKM := false
  ENABLE_QRNG_DLKM := true
  ENABLE_SMMU_PROXY := false
  ENABLE_SMCINVOKE_DLKM := true
  ENABLE_TZLOG_DLKM := false
  ENABLE_QSEECOM_DLKM := false
endif #TARGET_USES_GY

# TEST Drivers (si_core_test, seccam_driver, hdcp_test, tornado_mod)
ifneq ($(TARGET_USES_QMAA), true)
    ENABLE_SST_INVOKE_TEST := true
    ENABLE_HDCP_TEST := true
    ENABLE_SI_CORE_TEST := true
    ENABLE_SECCAM_TEST := true
endif

ifeq ($(TARGET_USES_QMAA_OVERRIDE_SST_CLIENTS), true)
    ENABLE_SST_INVOKE_TEST := true
endif
ifeq ($(TARGET_KERNEL_DLKM_SECURE_MSM_OVERRIDE), true)
    ENABLE_HDCP_TEST := true
    ENABLE_SECCAM_TEST := true
    ENABLE_SI_CORE_TEST := true
endif
ifeq ($(ENABLE_HDCP_DP), true)
    ENABLE_HDCP_TEST := true
endif

# Disabling test drivers for GY targets
ifeq ($(TARGET_BOARD_AUTO), true)
  ENABLE_HDCP_TEST := false
  ENABLE_SECCAM_TEST := false
  ENABLE_SI_CORE_TEST := false
  ENABLE_SST_INVOKE_TEST := false
endif #TARGET_BOARD_AUTO

ifeq ($(ENABLE_QCRYPTO_DLKM), true)
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/qcedev-mod_dlkm.ko \
      $(KERNEL_MODULES_OUT)/qcrypto-msm_dlkm.ko \
      $(KERNEL_MODULES_OUT)/qce50_dlkm.ko
endif #ENABLE_QCRYPTO_DLKM

ifeq ($(ENABLE_QRNG_DLKM), true)
  BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/qrng_dlkm.ko
  ifeq ($(ENABLE_HYP), true)
    BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/qrng_dlkm.ko
    BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/qrng_dlkm.ko
  endif # ENABLE_HYP
endif #ENABLE_QRNG_DLKM

ifeq ($(ENABLE_HDCP_QSEECOM_DLKM), true)
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/hdcp_qseecom_dlkm.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/hdcp_qseecom_dlkm.ko
endif #ENABLE_HDCP_QSEECOM_DLKM

ifeq ($(ENABLE_SMMU_PROXY), true)
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/smmu_proxy_dlkm.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/smmu_proxy_dlkm.ko
endif #ENABLE_SMMU_PROXY

ifeq ($(ENABLE_SMCINVOKE_DLKM), true)
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/smcinvoke_dlkm.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/smcinvoke_dlkm.ko
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/smcinvoke_dlkm.ko
endif #ENABLE_SMCINVOKE_DLKM

ifeq ($(ENABLE_TMECOM_INTF_DLKM), true)
BOARD_VENDOR_KERNEL_MODULES +=  $(KERNEL_MODULES_OUT)/tmecom-intf_dlkm.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/tmecom-intf_dlkm.ko
endif # ENABLE_TMECOM_INTF_DLKM

ifeq ($(ENABLE_TZLOG_DLKM), true)
BOARD_VENDOR_KERNEL_MODULES +=  $(KERNEL_MODULES_OUT)/tz_log_dlkm.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/tz_log_dlkm.ko
endif # ENABLE_TZLOG_DLKM

ifeq ($(ENABLE_QSEECOM_DLKM), true)
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/qseecom_dlkm.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/qseecom_dlkm.ko
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/qseecom_dlkm.ko
endif #ENABLE_QSEECOM_DLKM

ifeq ($(ENABLE_QCEDEV_FE), true)
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/qcedev_fe_dlkm.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/qcedev_fe_dlkm.ko
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/qcedev_fe_dlkm.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/qcedev_fe_dlkm.ko
endif #ENABLE_QCEDEV_FE

## TEST modules ##
ifeq ($(ENABLE_SI_CORE_TEST), true)
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/si_core_test.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/si_core_test.ko
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/si_core_test.ko
endif #ENABLE_SI_CORE_TEST

ifeq ($(ENABLE_SECCAM_TEST), true)
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/seccam_test_driver.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/seccam_test_driver.ko
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/seccam_test_driver.ko
endif #ENABLE_SECCAM_TEST

ifeq ($(ENABLE_HDCP_TEST), true)
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/hdcp2p2_test.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/hdcp2p2_test.ko
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/hdcp2p2_test.ko
endif #ENABLE_HDCP_TEST

ifeq ($(ENABLE_SST_INVOKE_TEST), true)
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/tornado_mod.ko
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/tornado_mod.ko
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += $(KERNEL_MODULES_OUT)/tornado_mod.ko
endif #ENABLE_SST_INVOKE_TEST
